name: RyanGolla
favicon: null
layout_spectrum: 0.7017307300120592
typography_spectrum: 0.668917644303292
title: Ryan Golla
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.2757085422053933
  lightness: 0.9758763525169343
  saturation: 0.25634896219708025
  rhythmicContrast: 0.5128184128552675
purpose: []
