name: Ryan Golla
favicon: null
layout_spectrum: 0.23586
typography_spectrum: 0.2509
title: Ryan Golla
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ff9a00'
    - '#fe3615'
    - '#ff4b0c'
    - '#ff7300'
    - '#ffbc01'
  brandStrength: 1
  lightness: 0
  saturation: 0.5
  rhythmicContrast: 1
purpose: []
